### ISSUE TITLE
Face normals became opposite after decoding from the encoded result

### ISSUE THREAD

**Issue by JiaxiangZheng** [google/draco#122]
After running the following procedure, the face normals of `mesh.drc.obj` become opposite for some faces

```
draco_encoder -qp 10 -qt 10 -qn 10 -i mesh.obj 
draco_decoder -i mesh.drc -o mesh.drc.obj
```

But if I encode with default parameter, the decode result seems good. [Here](https://www.dropbox.com/s/cosiykcxe1809ws/1000206.obj.zip?dl=0) is the original mesh file.

**Comment by ondys** [comment]
Thanks for the report. I was able to reproduce the issue and we will investigate it.

**Comment by ondys** [comment]
@JiaxiangZheng After investigating it a little bit more, it seams that the issue is that the problem is that the input model contains some rather thin features such as the lamp shade or the flower leaves. When you quantize it more aggressively, these thin features "collapse" so for example the inner ring of the lamp shade is going to have identical positions to the outer ring and the model can then be rendered incorrectly.

Based on my experiments, you need at least 13 bits of position quantization to represent this model correctly (`-qp 13`)

**Comment by JiaxiangZheng** [comment]
Thanks @ondys  for investigating this.
