### ISSUE TITLE
Create CMake Config/Targets files

### ISSUE THREAD

**Issue by KindDragon** [google/draco#130]
https://cmake.org/cmake/help/git-master/manual/cmake-packages.7.html#creating-packages

To support `find_package(draco)`

**Comment by tomfinegan** [comment]
I'm not quite sure that I understand the issue. What will find_package() support provide that you're not presently able to achieve using a draco install or via add_subdirectory()?

Reading through https://cmake.org/Wiki/CMake:How_To_Find_Libraries does not show a distinct advantage over the following options to use draco in another project.

find_package() support could be added in the future, perhaps via a draco module submitted to CMake, but for now to pull Draco into an existing project you'll need to clone the Draco git repo and do one of the following things:

1. Pass its path to add_subdirectory() in your own CMake scripts, add a dependency on the draco target via target_link_libraries(), and update your include paths via include_directories().
2. Build and install draco, update include paths via include_directories(), and link the library into your target(s) via target_link_libraries().
3. Follow the guidance at https://cmake.org/Wiki/CMake:How_To_Find_Libraries#Using_external_libraries_that_CMake_doesn.27t_yet_have_modules_for (basically the same as 1).

Typically I use find_package() only to locate external executables when needed from a CMake script (FindGit, FindPerl, FindPython for example). Are you aware of an advantage that searching for libraries using find_package() provides over the alternatives mentioned above?

Thanks for reporting the issue, and thanks in advance for any more information you can provide on the benefits of support find_package() instead of requiring use of add_subdirectory().

On a side note, generation of libdraco.pc (draco's pkg-config file) can be added to the install rule. I'll look into this myself sometime in the coming couple of weeks -- can't jump right in because of other commitments. I'd be happy to look at a pull request if it's something you're interested in adding.

**Comment by KindDragon** [comment]
We don't use `add_subdirectory` for external dependencies. We use Draco from our [Conan](https://www.conan.io/) and [Vcpkg](https://github.com/Microsoft/vcpkg) (for different projects), but it not so easy to use Draco from them (especially vcpkg).

JFYI https://youtu.be/bsXLMQ6WgIk?list=PL_AKIMJc4roXJldxjJGtH8PJb4dY6nN1D&t=2256

**Comment by tomfinegan** [comment]
Is what you're looking for fact cmake package management support? You want solution 2, but the process is a pain point because of its manual nature?

So, not necessarily direct support of find_package and/or a FindDraco module, though this probably makes the former work, but really a proper DracoConfig.cmake that gets generated and installed with the install rule?

**Comment by KindDragon** [comment]
> really a proper DracoConfig.cmake that gets generated and installed with the install rule

👍 Yes. I need proper CMake Config/Target scripts

**Comment by tomfinegan** [comment]
FindDraco.cmake has been added-- is this enough for Conan and Vcpkg?

**Comment by KindDragon** [comment]
It's better than nothing, but cmake configs easier to use in external project

**Comment by tomfinegan** [comment]
We're now generating and installing DracoConfig.cmake and FindDracoConfig.cmake-- I'm not sure if these do everything needed. Please open a new issue with any problems encountered. Thanks!

**Comment by KindDragon** [comment]
Ok, thanks
