### ISSUE TITLE
Points reodering, rationale ?

### ISSUE THREAD

**Issue by nyue** [google/draco#193]
Hi,

  I have the following OBJ file (a snippet of it)

`# 4 points`
`# 12 vertices`
`# 4 primitives`
`# Bounds: [-0.942810297, -0.333329707, -0.816497624] to [0.471405149, 1, 0.816497624]`
`g`
`v 0 1 0`
`v -0.942810297 -0.333329707 0`
`v 0.471405149 -0.333329707 0.816497624`
`v 0.471405149 -0.333329707 -0.816497624`

  I use draco_encoder to create the *.drc file

  When I dump the POSITION information, I see the following ordering

`Draco triangular mesh`
`        Num faces      4`
`        Num points     12`
`        Num attributes 3`
`                attribute[0] is of type Position`
`                        Position[0] = {-0.94281,-0.33333,4.98295e-05}`
`                        Position[1] = {0.471396,-0.33333,0.816498}`
`                        Position[2] = {2.68817e-05,1.00004,4.98295e-05}`
`                        Position[3] = {0.471396,-0.33333,-0.816498}`

  Is there a reason for the change in the ordering ?

  Is it in support for future features like Morton coding, LOD etc.

  I am writing a tool which which converts between Draco and other formats and doing a round-trip may not get be back the original content (floating precision not withstanding)

Cheers

**Comment by ondys** [comment]
@nyue One reason for reordering vertices is to improve compression of the attribute values. In general, when Draco encodes attribute values, it uses previously encoded values as predictors for the subsequent values. The accuracy of the prediction is extremely important for good compression and it heavily depends on the order in which the attribute values are encoded. While Draco could send an extra information to properly recreate the order of vertex indices in the decoded mesh, that would hurt the compression ratio quite a lot. One solution for this issue is to use sequential encoding method that is order preserving (`MESH_SEQUENTIAL_ENCODING`)
