### ISSUE TITLE
how to add .mtl  when decoding .drc in web page?

### ISSUE THREAD

**Issue by Saievo** [google/draco#197]
Hi, 
i don't konw how to use .mtl when decoding .drc files. i had read many issues in Draco project but even could't find some way to fix it.

if draco project can give some  demo, it will be very helpful, thanks!

like these demo:
three.js/examples/webgl_loader_obj_mtl.html
draco/javascript/example/webgl_loader_draco.html

model:
[one77.zip](https://github.com/google/draco/files/1298812/one77.zip)

**Comment by fanzhanggoogle** [comment]
Hi @Saievo , I assume the drc is encoded from .obj file. In that case, with our latest release, if you add `--metadata` when using `draco_encoder`, then the decoded obj file should preserve the material names in the obj file. Hope it helps.

**Comment by Saievo** [comment]
HI, @fanzhanggoogle 
thanks for your prompt reply.
The .drc file in the attachment is indeed compressed by the .obj file.
But I have two questions:
1. The "--metadata" option does not seem to work, and I compare it with or without the option, as the result .drc is the same.
2. My main request is to have a test page, which is similar to the two just mentioned, and it can load .drc and .mtl and render. Since I am interested in the excellent compression of the model, I want to use it in the project But I am not a professional 3d developer, so writing such a case would be more difficult.
So if you can provide a test page for decode  .drc and .mtl , for me is very helpful.
thank!

**Comment by fanzhanggoogle** [comment]
@Saievo Hi, for now Draco doesn't actually compress .mtl file but only the materials used in the obj file. So for your case, it should be the same as the webgl_loader_obj_mtl.html example if you provide the .mtl file and decoded obj file since the materials are preserved. Making an example rendering Draco encoded geometry along with the textures/materials is actually on our road map but probably won't get to that shortly.

**Comment by orient0254y** [comment]
I have write a demo:[https://github.com/orient0254y/load_mtl_drc_demo](url);and obj decomposition tool is here:[https://github.com/orient0254y/objFileDecomposition](url);
     Hope it helps.

**Comment by Saievo** [comment]
@orient0254y HI,Thank you very much for your reply and help.
I tried using your demo. when using your model , it was working properly.
But your model is cut off, I changed the demo into a single file, it seems that there has been a new problem: it seems that decoding has failed, but no error.
I try to use your blocking tool, but my obj model is cut into more than 300 files.I can hardly use it in such a situation.
Very confused, maybe you can use my uploaded file to try?
Thanks!

**Comment by orient0254y** [comment]
@Saievo If you want to add only one drc file to the scene,you must change the code or change the file name.you should read the rules I write.
obj model will be cut to many pieces is correct. you should know the obj structure.my obj file is build width Maya and 3dMax.It will contains many objects like,and these objects begin with:
#
# object *****
#
end width
# 6358 faces or # 14 polygons.
every object contains it's own attribute like "usemtl phong24SG",I cut the obj file due to these marks.
you can change the rules in my decomeposition.js file,or tell your 3D engineer partner to merge some small objects to big one.this step called "combine" in Maya and "attach" in 3DMax.such as a desk may be cut to desktop/deskleg/deskholder,then you will get only three small obj files.

**Comment by chenyangqu** [comment]
Currently Draco does not support groups in an obj file. This causes only one material be loaded(if any). ```javascript			
    var mtlLoader = new THREE.MTLLoader();
    mtlLoader.setPath( 'models/' );
			mtlLoader.load( 'texture.mtl', 
				function( materials ) {
					materials.preload();
						let material;
						material = materials.getAsArray()[1];
						dracoLoader.setPath( 'models/' );
						dracoLoader.load( 'draco.drc', function ( geometry ) {
							geometry.computeVertexNormals();
							var mesh = new THREE.Mesh( geometry, material );
							scene.add( mesh );
						},onProgress,onError );
					});```
 When DRACOLoader.js loading geometries, it DOES NOT add "groups" to the  THREE.BufferGeometry class rather than use .addgoups() functions.

**Comment by chenyangqu** [comment]
Currently Draco does not support groups in an obj file. This causes only one material be loaded(if any). `
    var mtlLoader = new THREE.MTLLoader();
    mtlLoader.setPath( 'models/' );
    mtlLoader.load( 'texture.mtl', 
    function( materials ) {
    materials.preload();
    let material;
						material = materials.getAsArray()[1];
						dracoLoader.setPath( 'models/' );
						dracoLoader.load( 'draco.drc', function ( geometry ) {
							geometry.computeVertexNormals();
							var mesh = new THREE.Mesh( geometry, material );
							scene.add( mesh );
						},onProgress,onError );
					});
`
 When DRACOLoader.js loading geometries, it DOES NOT add "groups" to the  THREE.BufferGeometry class rather than use .addgoups() functions.

**Comment by aruni445** [comment]
> Hi,
> i don't konw how to use .mtl when decoding .drc files. i had read many issues in Draco project but even could't find some way to fix it.
> 
> if draco project can give some demo, it will be very helpful, thanks!
> 
> like these demo:
> three.js/examples/webgl_loader_obj_mtl.html
> draco/javascript/example/webgl_loader_draco.html
> 
> model:
> [one77.zip](https://github.com/google/draco/files/1298812/one77.zip)

Hi @Saievo , I hope you are doing well. I am facing the same issue which you have encountered a long back. If you have the answer please help me out.

I have converted the .obj file to .drc. While loading the .drc file in threejs, I am unable to get the material(.mtl). Is there any way to get the material(.mtl file which is present in the row .obj)

Thanks
