### ISSUE TITLE
Using AddAttribute()

### ISSUE THREAD

**Issue by adishavit** [google/draco#28]
In the method:  

```
draco::PointCloud::AddAttribute(const` GeometryAttribute &att,  
                                bool identity_mapping,                // << THIS?
                                AttributeValueIndex::ValueType num_attribute_values);
```

What does the second argument `identity_mapping` do?
What situations determine if it should it be `true`/`false`?

`ObjDecoder` uses `false`, `PlyDecoder` uses `true`.

**Comment by ondys** [comment]
`identity_mapping` is used to specify mapping between point indices and attribute value indices.

if `identity_mapping` is `true`, the mapping is identity, meaning there will be one attribute value for each point of the parent `PointCloud` or `Mesh`. 
if `identity_mapping` is `false` the mapping is explicit, which means several points can use the same attribute value. The explicit mapping needs to be initialized manually using `PointAttribute::SetPointMapEntry()` method.

`ObjDecoder` uses `false` because the OBJ format specifies mapping between between points (vertices) and attribute values. On the other hand, PLY usually defines its attributes using the identity mapping (e.g., there are always three position values for every triangle, even when many of the position values are the same).

Note that these flags are not necessarily preserved all the way to the encoding stage. For example, for PLY files, after the model is loaded, Draco deduplicates all attribute values and point indices and the resulting mapping is going to be explicit as well.

See `PointCloud::DeduplicateAttributeValues()` and `PointCloud::DeduplicatePointIds()`.

We will update the code documentation.
