### ISSUE TITLE
Generic Attribute Data incorrect on Decompression

### ISSUE THREAD

**Issue by usmanshah** [google/draco#305]
I am trying to compress and uncompress a THREE. Geometry with Material ids using Typescript, in an angular4 app. 

My test Mesh has (non-indexed) has 24 faces,72 vertices and 11 materials

so i put in 72 material ids (a value for every vertex) into the DracoMesh, like so: 

```
const materialAttrId: number = meshBuilder.AddFloatAttributeToMesh(dracoMesh, encoderModule.GENERIC, numPoints, 1, materialIndices);
const metadataBuilder: any = new encoderModule.MetadataBuilder();
const materialMetadata: any = new encoderModule.Metadata();
metadataBuilder.AddStringEntry(materialMetadata, "name", "material");
meshBuilder.SetMetadataForAttribute(dracoMesh, materialAttrId, materialMetadata);
```

Then i compress the DracoMesh, like so:
```
const encodedData = new encoderModule.DracoInt8Array();
encoder.SetSpeedOptions(0, 0);
encoder.SetAttributeQuantization(encoderModule.POSITION, 14);
encoder.SetAttributeQuantization(encoderModule.TEX_COORD, 12);
encoder.SetAttributeQuantization(encoderModule.NORMAL, 10);
encoder.SetAttributeQuantization(encoderModule.GENERIC, 8)
encoder.SetEncodingMethod(encoderModule.MESH_EDGEBREAKER_ENCODING);
const encodedLen = encoder.EncodeMeshToDracoBuffer(dracoMesh, encodedData);
```

Then Decompress and get the data from the decompressed object, like so:
 
```
const materialAttId = decoder.GetAttributeIdByName(uncompressedDracoMesh, "material");
const materialAttribute = decoder.GetAttribute(uncompressedDracoMesh, materialAttId);
const materialAttributeData: any = new decoderModule.DracoInt32Array();
if (materialAttId !== -1) {
  decoder.GetAttributeIntForAllPoints(uncompressedDracoMesh, materialAttribute, materialAttributeData);
  const materialIds = [];

  for (let i = 0; i < uncompressedDracoMesh.num_points(); i += 1) {
    materialIds[i] = materialAttributeData.GetValue(i);
  }

}

```

The resulting **materialIds** array I get has incorrect materials assigned to some faces and the faces of those materials are missing in the array. 
I partly understand why the resulting array is not in order: the new order corresponds to the how the faces are arranged in the uncompressed mesh. 

**EXAMPLE** 
**Input**: `[0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9, 10, 10, 10, 11, 11, 11, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9, 10, 10, 10, 11, 11, 11]`

**Output**:` [5, 9, 0, 5, 5, 3, 1, 11, 9, 5, 5, 0, 6, 4, 3, 5, 4, 10, 1, 3, 10, 7, 11, 1, 7, 0, 6, 0, 9, 11, 0, 10, 4, 6, 0, 7, 1, 6, 3, 11, 4, 1, 9, 5, 6, 9, 1, 4, 7, 0, 9, 0, 5, 5, 5, 0, 7, 10, 3, 6, 5, 5, 10, 0, 11, 3, 0, 10, 7, 4, 11, 0] `

Note how material id 2 and 8 are missing in the output. 
Everything else (POSITION, TEX_COORD, NORMAL) comes back correctly after decompression.

Here is the model I am using: https://storage.googleapis.com/cm-platform-dev-media/rainbow-cube.obj

**Comment by ondys** [comment]
@usmanshah The middle code snipped is a little bit mangled but it looks like you are setting quantization for your material attribute. Since the data type is set to float, the attribute values are going to be quantized which is a lossy operation and the output values may be wrong. Try it without the quantization. (the compression rate will be worse in this case, but it should work.. we are planning to introduce support for proper integer attributes in javascript encoder api that would be ideal for this ..the compression would be much better in that case).

**Comment by JeremieA** [comment]
For a similar use-case (glTF JOINT attributes), I found that using GetAttributeFloatForAllPoints instead of GetAttributeIntForAllPoints followed by Math.round() to convert back to int can be a temporary fix for this issue (but proper integer attributes encoding from javascript would indeed be much better).

**Comment by ondys** [comment]
Support for integer attributes has been added to our Javascript encoder which should solve this issue
