### ISSUE TITLE
[Unity3D] Draco can't convert mesh with over 65k vertices

### ISSUE THREAD

**Issue by AnaRhisT94** [google/draco#322]
I'm using Unity3D,
Is there a solution for this? How should I approach that if not?

**Comment by fanzhanggoogle** [comment]
Hi, the DracoLoader should be able to handle meshes over 65k vertices. It will split the big mesh to multiple smaller meshes. Could you post your error or any information you got here?

**Comment by Sirokujira** [comment]
Looking at the Release Note, the correspondence is from Unity 2017.3.
https://blogs.unity3d.com/en/2017/12/19/unity-2017-3-is-here/

If it is done otherwise, it seems there is a corresponding way to downsample the point cloud.
https://www.microsoft.com/en-us/kinectforwindows/develop/downloads-docs.aspx
※ That things seem to be in the official sample code
