### ISSUE TITLE
Error C2666 on compile

### ISSUE THREAD

**Issue by mEscolar** [google/draco#325]
Good afternoon,

I have been trying to compile 1.2.4 release for a couple of days and when I try to compile I have errors c2666 'std :: fpos <_Mbstatet > :: operator == ': inside obj_decoder.obj.

My operating system is windows 7 x64, with visual studio 15.5.2 2017 and cmake 3.10.1.

After verifying my installation of visual studio, cmake and the project, just in case it was my mistake, I decided to go back to the last stable version that I used that is 1.1.0, in its commit b4211303fa5fe5d21f4f823b18c9d4978e77fb1f, and it worked perfectly.

A warm greeting and happy holidays

**Comment by ondys** [comment]
We just merged this [PR](https://github.com/google/draco/pull/321) that should fix your problem.

**Comment by Zephyrox** [comment]
I solved this by creating another variable for the file size, because the type should be streamoff and not streampos which auto file_size = file.tellg() will give you. 
`file_size = file.tellg() - file_size;`
is changed to:
`auto real_file_size = file.tellg() - file_size;`
remember to change to real_file_size on the lines a bit below.
