### ISSUE TITLE
Segfault on strange input

### ISSUE THREAD

**Issue by stuarteberg** [google/draco#356]
The draco encoder segfaults when processing the following mesh file.  As you can see, the mesh is clearly strange, (all vertexes are identical), but the OBJ file is not malformed per se.  Even if such meshes cannot be encoded, it would be nice to see an error message in such cases.  (It might spare bozos like me from some debugging effort.)

The command used was: 

```
draco_encoder -cl 5 -i mesh.obj -o mesh.drc
```

I'm using draco 1.0.1.  Sorry I haven't tested with a newer version yet.  I will do more testing if I get a chance.

```
v 0 0 0
v 0 0 0
v 0 0 0
f 3 2 1
```

**Comment by ondys** [comment]
thanks for the report. This will be fixed in the next release. Note that the encoding will fail in this case however, mostly because our main connectivity compression algorithm works only on non-degenerate faces (all degenerate faces are ignored). That being said, you should be able to encode this model using `-cl 0` which uses a different connectivity encoding method.

**Comment by stuarteberg** [comment]
Great, thanks for the update.  I assume that means this issue can be closed, but I'll leave that to you.

**Comment by stuarteberg** [comment]
Question for clarification:

>Note that the encoding will fail in this case

In the next release, will an error be returned, or will the degenerate face simply be discarded?  I guess I'd prefer it to be silently discarded.

**Comment by ondys** [comment]
Degenerate faces are discarded even in the current version, but in case there are no valid faces, the encoding will crash in the current version and fail in the next version

The other option would be to send an empty mesh but I'm not sure how useful would that be.
