### ISSUE TITLE
JavaScript example should likely use  webworker like OpenCTM example.

### ISSUE THREAD

**Issue by bhouston** [google/draco#46]
Decoding shouldn't happen on the main thread -- also this frees up more memory:

https://github.com/mrdoob/three.js/tree/dev/examples/js/loaders/ctm
https://github.com/mrdoob/three.js/blob/dev/examples/webgl_loader_ctm.html

This means that the decoder should return arraybuffers that are easy to pass from a webworker back to the main thread, which in the main thread is used to create a THREE.BufferGeometry.

**Comment by zynga-jpetersen** [comment]
Are there any known technical barriers to this being implemented?

From reading how the dracomodule is used within the dracoloader, there doesnt look like there is anything that would prevent implementing it in the ctm code pattern.

If no one knows of any reason it wouldnt work, I'm probably going to take a crack at it.

Since I dont think we want to import Three to the worker just to get the BufferGeometry out of it, I'll be looking at splitting up convertDracoGeometryTo3JS so it send back the attributes as maybe a {} of attributes and build the BufferGeometry in the worker's onmessage.

**Comment by zellski** [comment]
Strong +1 for this. If nobody else had done it in a month or so, we'd planned to tackle it ourselves.

So, @zynga-jpetersen, go forth and do battle!

**Comment by zynga-jpetersen** [comment]
Update on this, I tried the simplified approach, where I import the three js and draco into the worker. That both significantly increased the load times (I'm guessing from both sending data back and forth, but also all that code) and didnt result in good data since of course the THREE.Geometry wasnt transferable (I didnt necessarily expect this to work, just for a test). So as a second attempt at this I'm breaking up convertDracoGeometryTo3JS into 2 phases, 1 where it inflates the data from draco, and then builds the three geometry out of the results. Once I've got that working, I should be able to take phase 1 and move it off into a worker.

**Comment by drawmindmap** [comment]
Check out Babylon.js implements:
[babylon.dracoCompression.ts](url=https://github.com/BabylonJS/Babylon.js/blob/master/src/Mesh/Compression/babylon.dracoCompression.ts)
[KHR_draco_mesh_compression.ts](url=https://github.com/BabylonJS/Babylon.js/blob/master/loaders/src/glTF/2.0/Extensions/KHR_draco_mesh_compression.ts)

And you can even use draco_decoder.wasm in Web Worker.

**Comment by zynga-jpetersen** [comment]
I should have updated this sooner, my apologies.

I've been moved onto another project so I haven't had time to return to my refactoring.

**Comment by donmccurdy** [comment]
FYI, I've cross-filed this issue on three.js: https://github.com/mrdoob/three.js/issues/13648. There is some infrastructure in three.js's `examples/js/*` to support workers. But currently I don't think anyone is actively working on adding worker support to THREE.DRACOLoader.

**Comment by FrankGalligan** [comment]
three.js added web worker support. That can be used as an example.
