### ISSUE TITLE
Compression level is dramatically low when using it via C++ API in external project

### ISSUE THREAD

**Issue by wybieralski** [google/draco#470]
Hello,
I am using Draco library in my C++ project to compress STL/OBJ 3D meshes.
Draco::Mesh is being built from my-type Mesh using TriangleSoupMeshBuilder ( as in there https://github.com/google/draco/blob/master/src/draco/mesh/triangle_soup_mesh_builder_test.cc )
and being written in the file like:

`
draco::EncoderBuffer enc_buffer;
    draco::Encoder encoder;
    //    enc_buffer.Encode(0);

    encoder.EncodeMeshToBuffer(*draco_mesh, &enc_buffer);
    std::ofstream out("/home/lukasz/Desktop/cpr/cube.drc", std::ios::binary);
    if (out.is_open())
    {
        draco::EncoderOptions encoderOptions = draco::EncoderOptions::CreateDefaultOptions();
        encoderOptions.SetSpeed(1, 1);  // encode and decode speed between 0 and 10
        draco::WriteMeshIntoStream(draco_mesh.get(), out, draco::MESH_EDGEBREAKER_ENCODING, encoderOptions);
    }
    else
    {
        std::cerr << "Cant open stream to write" << std::endl;
    }
    out.close();
`
It works fine, the problem is that compression is very bad.
Using original ./draco_encoder I can compress big 3D 80MB mesh.OBJ  -> 400KB mesh.drc,
 with my API it is 80MB ->12 MB with encoderOptions.SetSpeed(10, 10); 
and 80MB->25MB with encoderOptions.SetSpeed(1, 1); 

I would like to know:
1. What is/are the reasons that compression is so bad and how can I check and/or fix it.
2. How to set compression level directly, as I didn't manage to do it other way than with setting encoderOptions.SetSpeed(1, 1)*.

Thank you for your help.

* I got it from here: https://github.com/google/draco/blob/master/src/draco/compression/encode.h

 // Sets the desired encoding and decoding speed for the given options.
  //
  //  0 = slowest speed, but the best compression.
  // 10 = fastest, but the worst compression.
  // -1 = undefined.
  //

**Comment by ondys** [comment]
It would be better to encode the geometry directly through draco::Encoder or draco::ExpertEncoder .. doing it via WriteMeshIntoStream is not that well supported at this moment.

The main reason for poor compression is mostly likely because no quantization is set for individual attributes and they are encoded losslessly (which Draco does not really compress at all). If you used draco::Encoder, you could for example set this to use 12 quantization bits for positions:
```
encoder.SetAttributeQuantization(GeometryAttribute::POSITION, 12);
```
Note that you may need to play with the quantization numbers to find what works for your data.

If you really want to use the WriteMeshIntoStream API you can still set quantization but it is somehow cumbersome. You can do that through encoderOptions as:
```
encoderOptions.SetAttributeInt(draco_mesh->GetNamedAttributeId(GeometryAttribute::POSITION), "quantization_bits", 14);
```

you should do that for any other attributes that are present in the mesh

**Comment by wybieralski** [comment]
Thank you very much, I will work on it.

**Comment by nlharr** [comment]
Also, remember to set the encoding method when encoding a mesh.
 encoder.SetEncodingMethod(MESH_EDGEBREAKER_ENCODING);
