### ISSUE TITLE
Coordinate system discrepancies

### ISSUE THREAD

**Issue by atteneder** [google/draco#567]
In the Draco specification I found nothing about a coordinate system definition (for example whether the content of draco file has to be specifically interpreted to be in a right-handed cartesian coordinate space).

And I think that makes sense. The user should have the freedom to use it for any system. As long as the whole pipeline (from encoding over decoding to rendering) is consistent, it should be fine.

It gets interesting when you have one content (draco file or draco compressed glTF) that has to be decoded to different systems. As an example, here's the bunny demo file from this project in Three.js (right-handed system):
<img width="359" alt="grafik" src="https://user-images.githubusercontent.com/2593014/69103138-dc76c500-0a64-11ea-9d65-33fd3fcc2df3.png">

And here imported in Unity (left-handed; incorrect: the Z-axis is flipped):
<img width="304" alt="grafik" src="https://user-images.githubusercontent.com/2593014/69103186-06c88280-0a65-11ea-8943-a0c69ea38d5f.png">

Wouldn't it make sense to flip the Z-axis in the Unity plugin by default in order to have consistency? This proposal makes even more sense as this would fix decoding of draco buffers inside glTF files (which definitely have [a defined coordinate system, namely right-handed y-up](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#coordinate-system-and-units)).

Another option is to add a parameter to `DecodeMeshForUnity` like so:
`int DecodeMeshForUnity(char *data, unsigned int length,
                       DracoToUnityMesh **tmp_mesh, bool flip_z_axis)`

I plan to prototype/implement this one way or another. but I wanted to get opinions as well.

Thanks

**Comment by atteneder** [comment]
Another thought:

The setting, whether to make conversions might also be a build-time setting (precompiler definition)

**Comment by atteneder** [comment]
That's more like it:
![grafik](https://user-images.githubusercontent.com/2593014/69198677-c2f17e00-0b35-11ea-9ef3-607a548e9e28.png)

src:
https://github.com/atteneder/draco/tree/z_flip

**Comment by FrankGalligan** [comment]
You are right we don't define the coordinate system. I was thinking about putting an option into the plug-in, but the issue is you will get some people using objects that already in the correct coordinate system and then it would be flipped when put into Unity. 

If developers are suing assets from glTF and want to import into Unity then they will already have to be cognizant of that fact. Or there is a glTF importer that will flip the coordinate system because glTF is defined to be the opposite.

With all that being said, we decided to keep the plug-in as is for now.
