### ISSUE TITLE
Xcode Build 'libdracodec_unity.a' Error

### ISSUE THREAD

**Issue by DrScatman** [google/draco#592]
Hello,

When utilizing the Draco package in Unity I am successfully able to build the Xcode project with Unity. However, when attempting to build the project in Xcode for iOS we receive the following errors:

- ![Image 3-29-20 at 9 18 PM](https://user-images.githubusercontent.com/49825641/77867213-57ff3480-7204-11ea-8ddd-0fb18b59971f.jpg)

Any help regarding this issue would be very much appreciated, as this project is for my CS Capstone class.

**Comment by DrScatman** [comment]
Also, I receive this warning message in Unity when building for iOS:

> Plugins: Couldn't open /Users/cisstudent/Documents/AR-Library/Library/PackageCache/com.atteneder.draco@c3ee8d09c1ab635bb37f4bb65eb0c7311b01df4e/Runtime/Plugins/x86_64/dracodec_unity.bundle/Contents/MacOS/dracodec_unity, error: dlopen(/Users/cisstudent/Documents/AR-Library/Library/PackageCache/com.atteneder.draco@c3ee8d09c1ab635bb37f4bb65eb0c7311b01df4e/Runtime/Plugins/x86_64/dracodec_unity.bundle/Contents/MacOS/dracodec_unity, 2): no suitable image found.  Did find:
	/Users/cisstudent/Documents/AR-Library/Library/PackageCache/com.atteneder.draco@c3ee8d09c1ab635bb37f4bb65eb0c7311b01df4e/Runtime/Plugins/x86_64/dracodec_unity.bundle/Contents/MacOS/dracodec_unity: file too short
	/Users/cisstudent/Documents/AR-Library/Library/PackageCache/com.atteneder.draco@c3ee8d09c1ab635bb37f4bb65eb0c7311b01df4e/Runtime/Plugins/x86_64/dracodec_unity.bundle/Contents/MacOS/dracodec_unity: file too short
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by tomfinegan** [comment]
In the future when filing bugs related to build errors please just copy/paste the error text from the build tool (or post a log file somewhere and link it). The screen shot is not very useful since the text can't be copy/pasted.

It sounds like you have an amd64 or x86 build of draco and you want to use it on arm64. Obviously you cannot do this. You'll need to build draco using the arm64-ios toolchain and use that build when linking your ios application, but the toolchain files do not support Xcode. You'll have to build the library and so using command line tools and then put the binaries where your Xcode project can find them.

I just built the unity bundle and it appears to be building correctly. This is the basic sequence, from within your draco repository:

1. mkdir build-arm64-ios 
2. cd build-arm64-ios
3. cmake .. -DBUILD_UNITY_PLUGIN=1 -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/arm64-ios.cmake
4. make

After make completes you can verify that you have an arm64 build by running file on dracodec_unity:
file dracodec_unity.bundle/dracodec_unity

The output should be:
dracodec_unity.bundle/dracodec_unity: Mach-O 64-bit bundle arm64

Also, quick question: Are you working with older draco sources or cross compiling? I'm not sure where libdracodec_unity.a is coming from. The unity build produces a bundle for ios/mac.

**Comment by ondys** [comment]
No response from the OP after 6 months. Closing for now.
