### ISSUE TITLE
Can anybody upload an iOS lib for unity?

### ISSUE THREAD

**Issue by FanEric** [google/draco#594]
I'm new to iOS and cmake, had spent a whole day on building iOS lib and failed again, I'm wondering why thers is Android, PC, Mac lib but not one for iOS. I've tried the special site for unity, and it couldn't work. Somebody help!

**Comment by tomfinegan** [comment]
Can you elaborate on what you're trying and where it's failing? I just built the unity bundle using the following commands on the git repo at head:

1. Clone draco or update existing clone.
2. cd path/to/draco
3. mkdir build-arm64-ios
4. cd build-arm64-ios
5. cmake .. -DBUILD_UNITY_PLUGIN=1 -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/arm64-ios.cmake
6. make

dracodec_unity.bundle was output at the root of the build directory. Using the file command reports an arm64 bundle:

$ file dracodec_unity.bundle/dracodec_unity
dracodec_unity.bundle/dracodec_unity: Mach-O 64-bit bundle arm64

**Comment by FanEric** [comment]
> Can you elaborate on what you're trying and where it's failing? I just built the unity bundle using the following commands on the git repo at head:
> 
> 1. Clone draco or update existing clone.
> 2. cd path/to/draco
> 3. mkdir build-arm64-ios
> 4. cd build-arm64-ios
> 5. cmake .. -DBUILD_UNITY_PLUGIN=1 -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/arm64-ios.cmake
> 6. make
> 
> dracodec_unity.bundle was output at the root of the build directory. Using the file command reports an arm64 bundle:
> 
> $ file dracodec_unity.bundle/dracodec_unity
> dracodec_unity.bundle/dracodec_unity: Mach-O 64-bit bundle arm64

Thank you, tomfinegan. I followed your step and everything goes fine. And what should I do with dracodec_unity.bundle? There is already a file with the same name in draco-master/unity/Plugin/, and it seems for Mac OS.  And I'm making iphone deploy in unity. Can you put more detail on this? Thank you very much!

**Comment by FanEric** [comment]
And I also tried 
"$ cmake path/to/draco -DCMAKE_TOOLCHAIN_FILE=path/to/draco/cmake/toolchains/arm64-ios.cmake
$ cmake --build ."
you mentioned in https://github.com/google/draco/commit/3b3cab31e5e75de851cd2eb588cd7ba8eec70f27 this page, it output libdraco.a, libdracodec.a and libdracoenc.a, I put them to Plugins/iOS folder in Unity and build, and fininally the xCode says library not found for -ldracodec

**Comment by tomfinegan** [comment]
I'm not very familiar with using Unity, so I can't help very much here. What I do know is that Draco usually lives in a subdirectory named Assets/Plugins within your Unity project. 

I am pretty sure that Unity requires you to use the bundle for MacOS and iOS. You'll have to look through Unity docs or ask someone more familiar how to proceed. I think all you need to find out is where the iOS bundle needs to be relative to your project, and then how to reference it.

> you mentioned in 3b3cab3 this page, it output libdraco.a, libdracodec.a and libdracoenc.a, I put them to Plugins/iOS folder in Unity and build, and fininally the xCode says library not found for -ldracodec

It's possible that for iOS that you must still use a static library. If that is the case the directions in https://github.com/google/draco/commit/3b3cab31e5e75de851cd2eb588cd7ba8eec70f27#commitcomment-29056885 are likely useful. However I want to caution you that things may have changed within Unity since that was posted in 2018 and those directions could be incorrect now.

I don't currently have an iOS device to test this, and I won't be able to gain access to one until the shelter in place is lifted in California. This unfortunately means you're basically on your own. I will leave this issue open and assigned to me in case it turns out you must build a static lib for iOS (because in that case there is a problem that needs to be handled in the draco build when targeting iOS).

Good luck!

**Comment by FrankGalligan** [comment]
@FanEric I think @atteneder has an ios lib on https://gitlab.com/atteneder/DracoUnity

**Comment by atteneder** [comment]
> @FanEric I think @atteneder has an ios lib on https://gitlab.com/atteneder/DracoUnity

Indeed!
It has pre-built binaries for all major platforms, so it should be easy to get working as a Unity developer.

**Comment by FanEric** [comment]
@tomfinegan Thank you all the same. 
I'm not sure if static lib is a must, but I've seen some unity projects, they all use static lib for iOS.
Maybe the following pages may help if you are going to handle this issue.
https://docs.unity3d.com/Manual/PluginsForIOS.html
https://www.bugsnag.com/blog/building-native-plugins-for-unity-games
And finally hope the situation finish soon and everything is ok

**Comment by FanEric** [comment]
@atteneder I do saw your repository and the DracoUnityDemo, but strange thing is it just didn't work. The console says Failed:Decoding error. And on Mac, it also says EntryPointNotFoundException: DecodeMeshForUnity. I have allowed 'unsafe' code. Is there something else should done before I run the demo?

**Comment by FanEric** [comment]
Finally got the .a lib by generating xCode project first. Here is the step:
1. Run 
cmake ../draco -G Xcode \
-DCMAKE_SYSTEM_NAME=iOS \
-DCMAKE_OSX_ARCHITECTURES=arm64 \
-DCMAKE_OSX_DEPLOYMENT_TARGET=10.0 \
-DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO \
-DBUILD_FOR_GLTF=TRUE \
-DBUILD_UNITY_PLUGIN=TRUE

2.Open the generated project using xCode

3.Config your development team both in project and target

4.Select your Device(not a simulator) and run. The .a file should in yourbuildpath/Debug-iphones/libdracodec_unity.a

**Comment by atteneder** [comment]
> @atteneder I do saw your repository and the DracoUnityDemo, but strange thing is it just didn't work. The console says Failed:Decoding error. And on Mac, it also says EntryPointNotFoundException: DecodeMeshForUnity. I have allowed 'unsafe' code. Is there something else should done before I run the demo?

I kind of missed this message, sorry.
Unfortunately many sturggle with installing due to GIT LFS not working properly or some other Package Manager bug.
All I can offer is help if you file an issue with details.

Glad you got this working though!
