### ISSUE TITLE
 TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by evehal** [google/draco#600]
............
const decoderModule = draco3d.createDecoderModule({});
const encoderModule = draco3d.createEncoderModule({});
const encoder = new encoderModule.Encoder();
.............
in javascript example,u can create encoder after decoder created,but if u try to create encoder without decoder,u will get a error: TypeError: Cannot read property 'apply' of undefined
so,i guess js api does not support create encoder first
but c++ api works fine,right?

**Comment by FrankGalligan** [comment]
So the issue is loading of the JavaScript modules are done asynchronously. 

You can see [here](https://github.com/google/draco/blob/master/javascript/time_draco_decode.html#L59) we pass a callback function through `onModuleLoaded` to be called when the module is loaded and we are allowed to use it.

In the next release I will update the npm example code.

Try this to see if it helps:
// Global variables to keep track of which modules have been intiailized.
let encoderModuleInitialized = false;
let decoderModuleInitialized = false;

// Callback function when encoder module has been intialized.
let dracoEncoderType = {};
dracoEncoderType['onModuleLoaded'] = function(module) {
  encoderModuleInitialized = true;
  console.log('Encoder Module Initialized!');
  moduleInitialized();
};

// Callback function when decoder module has been intialized.
let dracoDecoderType = {};
dracoDecoderType['onModuleLoaded'] = function(module) {
  decoderModuleInitialized = true;
  console.log('Decoder Module Initialized!');
  moduleInitialized();
};

// The code to create the encoder and decoder modules is asynchronous. draco3d
// will call the 'onModuleLoaded' callback when the different modules have been
// fully initialized.
const encoderModule = draco3d.createEncoderModule(dracoEncoderType);
const decoderModule = draco3d.createDecoderModule(dracoDecoderType);

function moduleInitialized() {
  if (encoderModuleInitialized && decoderModuleInitialized) {
    console.log('Both Modules Initialized!');
    let encoder = new encoderModule.Encoder();
    let decoder = new decoderModule.Decoder();
    cleanup(encoder, decoder);
  }
}

function cleanup(encoder, decoder) {
  encoderModule.destroy(encoder);
  decoderModule.destroy(decoder);
}

**Comment by Spaceman007** [comment]
Thanks. I wrote like this, and it works
```javascript
const DracoEncoderModule = require( '../draco_encoder' )

const encoderModule = DracoEncoderModule( {
    onModuleLoaded: function () {
        console.log( 'module loaded' )
        const encoder = new encoderModule.Encoder()
        const meshBuilder = new encoderModule.MeshBuilder()
    }
} )
```
