### ISSUE TITLE
Unity import bone weights

### ISSUE THREAD

**Issue by Siccity** [google/draco#632]
I'm working on [GLTFUtility](https://github.com/Siccity/GLTFUtility) trying to get draco compression working. So far so good. I stumbled into an issue with importing weights. It seems like `enum AttributeType` in [DracoMeshLoader.cs](https://github.com/google/draco/blob/master/unity/DracoMeshLoader.cs)  is used to load the different parts of the mesh (positions, normals, colors etc), but no value exists for weight. There is a generic value, but I'm unsure how to extract weights from this.

Can I get any pointers here?

**Comment by FrankGalligan** [comment]
So you can see [here](https://github.com/google/draco/blob/master/unity/DracoMeshLoader.cs#L255) the script currently does not do anything with generic data.

The issue is for the glTF attributes Weights, Joints, and Tangents, they will be encoded as [generic data](https://github.com/google/draco/blob/master/src/draco/attributes/geometry_attribute.h#L40) in a Draco mesh.

The script would need to be changed to pass in a way to map the glTF attributes to the unique Draco mesh generic attributes. Most likely would need to pass it in to the function [here](https://github.com/google/draco/blob/master/unity/DracoMeshLoader.cs#L141).

**Comment by FrankGalligan** [comment]
@atteneder Does https://github.com/atteneder/DracoUnity have an example for this?

**Comment by atteneder** [comment]
Not sure if there's an example, but I solved this in DracoUnity and my [fork of draco](https://github.com/atteneder/draco). It's not based on the latest version though and I'm not sure what changes I missed so far.

**Comment by Siccity** [comment]
I solved my issue here: https://github.com/KhronosGroup/glTF/issues/1880
