### ISSUE TITLE
Improved Documentation on Building Draco

### ISSUE THREAD

**Issue by Christopher-Hayes** [google/draco#670]
Hello, I think the documentation could be improved a little when it comes to building the project. My use-case:

> To use the `draco_encoder` binary to encode glTF/GLB models from the CLI for my project

I imagine that use-case can't be that unusual. But, the documentation doesn't seem to mention how to build the CLI binaries, it focuses on how to pull Draco into your repository.

### Potential Improvements

1. There isn't a section for building the CLI tool binaries. One can guess if you follow the documentation for building examples with CMake and then run `make` you'll get the encoding/decoding binaries you need. But, if the documentation told you exactly what you need to do would help a lot.
2. The documentation has a section for building with CMake, but it doesn't mention the final step is to run `make` on the generated `Makefile`. It does mention a `Makefile` is generated, and I think it's obvious to most people what to do next, but still this step would help for clarity’s sake. That `make` step is mentioned further down for WebAssembly, JS, iOS, and Android, just not up top for Windows, Mac, and Linux.

**Comment by tomfinegan** [comment]
I understand that CMake can make things a little confusing, but what you're requesting won't help everyone. Makefiles are not necessarily the default output from CMake. CMake generates build systems for many different build environments. This includes Makefiles, but it also includes Visual Studio, Xcode, Ninja, and many more. 

Is it not obvious that you have to generate build files and then run the build to produce binaries? I could add a line of text explicitly stating that the build must be run after CMake build generation completes. Would that help?

With regard to the Emscripten stuff-- those systems are a little less flexible, and, at least at the time the docs were written, the systems always ended up using makefiles. Since that was the case the docs could be a little more specific.

**Comment by tomfinegan** [comment]
Closing due to lack of response.
