### ISSUE TITLE
DracoConfig.cmake and friends

### ISSUE THREAD

**Issue by hobu** [google/draco#671]
The 1.4.0 release significantly changed the CMake situation for Draco, and this is having some downstream impacts on users such as [Conda Forge](https://github.com/conda-forge/draco-feedstock/). It's not clear if these changes were intentional. Are you interested in patches on this topic?

Specifically,

* `draco-config.cmake` is placed in `share/cmake` prefix (instead of `lib/cmake`)
* `DracoConfig.cmake` no longer being installed
* `DracoConfigVersion.cmake` is no longer installed
* Defining `DRACO_LIBRARY_DIR` in the config would be helpful
* FindDraco.cmake no longer installed

**Comment by tomfinegan** [comment]
> The 1.4.0 release significantly changed the CMake situation for Draco, and this is having some downstream impacts on users such as [Conda Forge](https://github.com/conda-forge/draco-feedstock/). It's not clear if these changes were intentional. Are you interested in patches on this topic?
> 

Patches are always welcome, but some of the changes were intentional. The entire CMake build was rebuilt for the v1.4 release due to the high degree of difficulty in maintaining the previous system.

> Specifically,
> 
> * `draco-config.cmake` is placed in `share/cmake` prefix (instead of `lib/cmake`)

This location is $CMAKE_INSTALL_PREFIX/$CMAKE_INSTALL_DATAROOTDIR, and is the correct location for such files based on my reading of the GNUInstallDirs documentation provided by CMake. The previous location was likely something I made up a few years ago.

> * `DracoConfig.cmake` no longer being installed

DracoConfig.cmake expands to this on my system:

```
set(draco_VERSION "1.3.6")
####### Expanded from @PACKAGE_INIT@ by configure_package_config_file() #######
####### Any changes to this file will be overwritten by the next CMake run ####
####### The input file was DracoConfig.cmake                            ########
get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)
macro(set_and_check _var _file)
  set(${_var} "${_file}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "File or directory ${_file} referenced by variable ${_var} does not exist !")
  endif()
endmacro()
####################################################################################
set_and_check(draco_INCLUDE_DIR "${PACKAGE_PREFIX_DIR}/include/draco")
set_and_check(draco_LIBRARY_DIR "${PACKAGE_PREFIX_DIR}/lib")
```

Those paths are both incorrect, and I'm not sure they were ever correct. DracoConfig.cmake was dropped from the install because it did not work as intended.

> * `DracoConfigVersion.cmake` is no longer installed

I would be happy to review a patch that sets DRACO_VERSION in draco_config.cmake if that's something that downstream users need. The pkg-config file already includes the version information, and adding the information to the CMake config file seems reasonable.

As for the other information that DracoConfigVersion.cmake attempted to provide: How was it being used in your projects?

> * Defining `DRACO_LIBRARY_DIR` in the config would be helpful
> * FindDraco.cmake no longer installed

During integration with USD we found that these files were not actually useful, but they were left in the repository in case something like this issue ended up being raised. Downstream projects are welcome to integrate these files into their projects, but they are unlikely to be updated unless a compelling reason is provided. 

For example, why is $DRACO_LIBRARY_DIR needed? For a system level install of draco no include or library paths should be needed-- includes should just work, as should linking draco. 

For a custom draco install location I recommend doing something like what USD does with their [FindDraco.cmake](https://github.com/PixarAnimationStudios/USD/blob/release/cmake/modules/FindDraco.cmake): set DRACO_ROOT in your project, and then look for necessary files using simple CMake commands.

All that being said:

> some downstream impacts on users such as Conda Forge

What are these impacts-- Are there issues somewhere that explain problems people are running into, or is this situation here more of a problem with some packaging scripts that will need to be updated because Draco changed?

**Comment by hobu** [comment]
> What are these impacts-- Are there issues somewhere that explain problems people are running into, or is this situation here more of a problem with some packaging scripts that will need to be updated because Draco changed?

Mostly just the need to update other packaging scripts based on it. Given this was intentional, we will work to adapt to what you are maintaining going forward.
