### ISSUE TITLE
Typescript Support?

### ISSUE THREAD

**Issue by oldbane** [google/draco#689]
Are there any existing types definitions for the javascript decoder API?

**Comment by tomfinegan** [comment]
We have very little experience with typescript on the Draco team. Can you elaborate a bit on what you're looking for? 

FWIW the JS encoder and decoder provide typed interfaces that are exposed via our IDL[1,2] files, but I'm assuming you're aware of those and that more is needed. 

[1] https://github.com/google/draco/blob/master/src/draco/javascript/emscripten/draco_web_decoder.idl
[2] https://github.com/google/draco/blob/master/src/draco/javascript/emscripten/draco_web_encoder.idl

**Comment by donmccurdy** [comment]
@tomfinegan TypeScript developers can use dependencies written either in TypeScript or in JavaScript. Since libraries written in JS don't inherently have type information, type checking cannot infer much about those dependencies without some additional information in type definition files (`.d.ts`).... the dependency is still usable in TS without that information, but it's more inconvenient an error-prone for TS developers. There are basically three ways to provide those type definitions:

1. Write, and maintain by hand, a `.d.ts` type definition file for the library's JS interface, published to NPM within the package.
2. Convert the library itself to TypeScript, in which case type definitions are generated automatically.
3. Do not officially support TypeScript, but recommend that users contribute type definitions to the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) project themselves. Users could then do something like `npm install --save draco3d @types/draco3d`. 

I've already written some "best guess" type definitions for the `draco3d` (and `draco3dgltf`) package, covering both encoding and decoding:

https://github.com/donmccurdy/glTF-Transform/blob/main/packages/extensions/src/types/draco3d.ts

In the past I've found (1) to be a pretty unpleasant thing as a maintainer (and three.js had the same experience), so I can't commit to maintain that file for the use of other projects, and I wouldn't advise the Draco team to try to maintain the file either. But, it would be a good starting point if someone would like to publish it to DefinitelyTyped, and then anyone can contribute to it there.

**Comment by repalash** [comment]
Since the interfaces are already written in IDL, it might be possible to convert directly to d.ts with a build step with libraries like this: https://github.com/giniedp/webidl2ts

**Comment by donmccurdy** [comment]
Opened PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54995

**Comment by donmccurdy** [comment]
Published:

- `@types/draco3d`: [pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54995) | [npm](https://www.npmjs.com/package/@types/draco3d)
- `@types/draco3dgltf`: [pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55333) | [npm](https://www.npmjs.com/package/@types/draco3dgltf)

**Comment by danem** [comment]
@donmccurdy So something like this should be working?

```typescript
import * as three from "three"
import * as draco from "draco3d"

const GOOGLE_URL = "https://www.gstatic.com/draco/versioned/decoders/1.4.1/"

function _loadFile (decoder_path: string, url: string, responseType: string) : Promise<string | ArrayBuffer>{
    let loader = new three.FileLoader();
    loader.setPath(decoder_path);
    loader.setResponseType(responseType);
    return new Promise((resolve, reject) =>{
        loader.load(url, resolve, undefined, reject);
    });
}

function loadDracoDecoder () {
    _loadFile(GOOGLE_URL, "draco_decoder.wasm", "arraybuffer")
        .then((buffer) => {
            return draco.createDecoderModule({
                wasmBinary: buffer
            });
        })
        .then((module) => {
            console.log("Loaded module");
        });
}
```

The above code results in this error message:

```
TypeError: WebAssembly.instantiate(): Import #0 module="env" error: module is not an object or function)
```

**Comment by tomfinegan** [comment]
It appears that the necessary work for this issue was handled in Don's PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54995

Closing this. Please feel free to comment further if this should be reopened-- filing another issue is always welcome as well.

Thanks!
