### ISSUE TITLE
Identical vertices don't result in the same position after draco compression, leading to gaps between meshes

### ISSUE THREAD

**Issue by hybridherbst** [google/draco#713]
We have some meshes that are split in chunks (one glb file, multiple meshes inside). The chunk borders align perfectly (the vertices have identical positions). However, after draco compression, there are noticeable gaps between these chunks.
My assumption is that somehow the quantization for the same input data results in different output data; is this expected, or is there a way to optimize a file "globally" instead of per-mesh?

**Before/After**
![image](https://user-images.githubusercontent.com/2693840/119021807-287b3080-b9a0-11eb-8b86-ac79f05e0a55.png)
![image](https://user-images.githubusercontent.com/2693840/119021832-2dd87b00-b9a0-11eb-9555-7c97e2e773a1.png)

**Before/After (closeup)**
![image](https://user-images.githubusercontent.com/2693840/119021924-4a74b300-b9a0-11eb-8fa4-bef8392c0446.png)
![image](https://user-images.githubusercontent.com/2693840/119021938-4f396700-b9a0-11eb-9972-8e10f4ee49d7.png)

**Comment by PurpleSwords** [comment]
I also encountered this problem. In the source code, I found that Draco uses mesh as the unit for processing, so there will be some differences in quantification between different meshes.

My current solution is to use SetAttributeExplicitQuantization instead of SetAttributeQuantization, and manually set all mesh quantization ranges to the same value. In this way, for the same value, the result of quantization will remain the same.

Obviously, in order to unify the quantization range, I have to use larger parameters for setting, which will reduce the accuracy and increase the file size——But it has no cracks.:rofl::rofl::rofl:

**Comment by hybridherbst** [comment]
Thanks for investigating this!
@donmccurdy I believe this is not supported in gltf-transform CLI or regular right now, is that correct?

**Comment by donmccurdy** [comment]
Right, currently glTF-Transform is letting Draco determine the quantization parameters, so that's inherently per-primitive. I think glTF-Pipeline has implemented what you're describing, under the `--draco.unifiedQuantization` option, and I'd be curious to know if you get better results from that?

This doesn't sound too complicated to add to glTF-Transform, so I've filed that as https://github.com/donmccurdy/glTF-Transform/issues/257.

**Comment by hybridherbst** [comment]
Sorry for the delay, just verified that indeed the `--draco.unifiedQuantization true` option in gltf-pipeline fixes the issue:

`unifiedQuantization false`
![image](https://user-images.githubusercontent.com/2693840/120202031-62f98e80-c226-11eb-86b2-d4f7ecab0f3c.png)

`unifiedQuantization true`
![image](https://user-images.githubusercontent.com/2693840/120202086-74429b00-c226-11eb-988f-2a886147ec79.png)

So I think this issue here can be closed (since it seems to be "by design" that draco does this by default, and there's a flag that fixes the issue at hand).

**Comment by donmccurdy** [comment]
Also note that you can use higher precision (e.g. 24 bits) for the position attribute, which may help here.

Would you be able to share the asset above? I'd be interested in testing an implementation with a global quantization volume in glTF-Transform later.

**Comment by hybridherbst** [comment]
Yep, should have mentioned, I bumped the precision from 14 bit to 16 bit in this case to get rid of some noticeable imperfections.
Generally it wasn't easy to match the behaviour of gltf-pipeline to that of gltf-transform - they seem to have very different defaults, and I didn't find all the matching numbers.

I sent you the file url via Khronos Slack - I can also send it via mail if that's better :)

**Comment by donmccurdy** [comment]
Adding this option to gltf-transform soon, feel free to track this in https://github.com/donmccurdy/glTF-Transform/pull/272.
