### ISSUE TITLE
draco_decoder.exe does not support root directory as output path

### ISSUE THREAD

**Issue by hoxily** [google/draco#759]
When use draco_decoder to convert draco data to obj format via following command line arguments, it gives error `src\draco\io\file_writer_factory.cc:41 (OpenWriter): No file writer able to open output.`
```
C:\Users\linctex\workspace\google-draco\build\Debug>draco_decoder -o D:\output.obj -i D:\linctex\downloads\WOV1018194-50-particle\sco.co.0-2707
StdioFileWriter::registered_in_factory_: 1.
C:\Users\linctex\workspace\google-draco\src\draco\io\file_writer_factory.cc:41 (OpenWriter): No file writer able to open output.
Failed to store the decoded mesh as OBJ.
```
If I create directory D:\objs，and change command line to following:
```
draco_decoder -o D:\objs\output.obj -i D:\linctex\downloads\WOV1018194-50-particle\sco.co.0-2707
```
It works perfectly.

[draco-data.zip](https://github.com/google/draco/files/7416499/draco-data.zip)

**Comment by tomfinegan** [comment]
The underlying bug is fixed upstream. Calling stat() on a drive letter while omitting the trailing path separator does not work on Windows, and that is fixed. 

However, many Windows systems are not configured to allow unprivileged users to write directly to the root of a drive. On systems configured that way users are on their own wrt the required write permissions. Draco is not going to present a UAC dialog and ask for admin privileges.
