### ISSUE TITLE
Can quantification and prediction be done independently in Draco

### ISSUE THREAD

**Issue by liqingzhaomingcheng** [google/draco#767]
I want to encode and decode texture coordinates and normals without positions. I want to know whether these two attributes will use the value of position in the prediction and whether they can be removed from the dependence of position in the RearrangeAttributesEncoders() funcition.

**Comment by ondys** [comment]
In general texture coordinates and normals need position attribute to be present (unless they use basic predictors such as parallelogram that don't rely on other attributes). It should be possible to set prediction method for a given attribute via ExpertEncoder::SetAttributePredictionScheme() method. That being said, removing position attribute would still probably not work because it is used for connectivity encoding.

You should be able to use pre-quantized positions though (basically just provide a position attribute with an integer data type).

**Comment by liqingzhaomingcheng** [comment]
@ondys Thank you! In fact, I used position attribute in the encoder, but I did not encode it into buffer, so the connectivity can be encoded. However, I noticed that position attribute was used when decoding texture coordinates at the decoder.That's why I ask the question. I'll try to use parallelogram prediction method.
Thank you very much!

**Comment by liqingzhaomingcheng** [comment]
@ondys I'm sorry to bother you again. I found that when I compress obJ files, I set qp,qt,qn to 0 because i want a lossless result, draco didn't compress these attributes, but just writes them directly to bitstream. I wonder why they are not predicted and entropy coded, does this process cause some loss to them.

**Comment by ondys** [comment]
Draco supports prediction / entropy coding only on integer values (quantized or pre-quantized values). Floating point values are currently stored without any compression.

**Comment by liqingzhaomingcheng** [comment]
@ondys but in obj_decoder, ObjDecoder::ParseVertexPosition() function treats the data directly as float,even if the input is integer values. So do I have to modify this part myself if I want to read in integers?
![image](https://user-images.githubusercontent.com/72381393/142333013-397e9f28-8954-42d6-ba0b-c7fbc5fc06b9.png)

**Comment by ondys** [comment]
That's the limitation of the obj format. Obj doesn't really specify data type so Draco treats all values as floats. You would have to either modify the loader yourself or alternatively you can replace the attribute with an integer attribute after it is loaded.
