### ISSUE TITLE
IPFS NODE JS DRACO decode - help

### ISSUE THREAD

**Issue by srink007** [google/draco#791]
I am a 3d artist and I am working with my dev friend.
He packaged a 3d model for me to use a custom 
glb player , i have used draco compression,
he said it is playing locally ,
but when hosted to IPFS , it wont 
because of how node js works internally.
i am looking forward to a workaround.
Can someone please help

**Comment by tomfinegan** [comment]
The Draco project has no expertise in IPFS use. 

> he said it is playing locally

The model working locally on a certain system is a hint that the player has dependencies that your dev friend is unaware of, and that those dependencies on the working system must be present on other systems in order for the custom player to work correctly. 

Quite a bit more information would be needed for us to help you with this, and from the report it sounds like the issue is well outside the scope of the Draco project. Please add more information about what's actually happening.
