### ISSUE TITLE
CMake: install dll in bin folder & allow to not install static

### ISSUE THREAD

**Issue by SpaceIm** [google/draco#834]
I maintain draco recipe in conan-center (public repository of conan package manager), and we have a recurrent patch related to CMake installation of draco:

- dll is installed in `lib` folder, which is not a standard layout on Windows where dll should go into `bin` folder.

- Except for msvc, static & shared are built & installed together since 1.4.0. It would be nice if there was a way to disable installation of static when `BUILD_SHARED_LIBS ON` (packaging both flavors in the same build is not allowed in conan-center, and I think also in vcpkg).

Basically here is our patch for 1.5.2:

```patch
--- a/cmake/draco_install.cmake
+++ b/cmake/draco_install.cmake
@@ -84,12 +84,14 @@ macro(draco_setup_install_target)
   endif()
 
   if(MSVC)
-    install(TARGETS draco DESTINATION "${libs_path}")
+    install(TARGETS draco RUNTIME DESTINATION bin ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
   else()
+    if(NOT BUILD_SHARED_LIBS)
     install(TARGETS draco_static DESTINATION "${libs_path}")
+    endif()
 
     if(BUILD_SHARED_LIBS)
-      install(TARGETS draco_shared DESTINATION "${libs_path}")
+      install(TARGETS draco_shared RUNTIME DESTINATION bin ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
     endif()
   endif()
 
```

**Comment by SpaceIm** [comment]
I can submit a PR.
What would you prefer regarding installation of static lib? A `DRACO_INSTALL_STATIC` which is available if `NOT MSVC and BUILD_SHARED_LIBS`, and defaulted to ON to keep current behavior by default?

**Comment by tomfinegan** [comment]
There are a couple things going on here:

1) The lib _must_ be installed with the dll. The lib file is actually an import library. Trying to use draco without the import library when BUILD_SHARED_LIBS is enabled will not work. It's required at link time when building executables that use the draco dll. 

2) I agree that the dll (and lib, because of the above) should be installed to the bin dir on Windows side-by-side with the tools. 

Regarding 1,  the draco install rule will not be changed re the installation of the import lib: doing so would break usage of the DLL for users using installed draco to link it into their projects. We're not breaking that functionality in order to appease opinionated package managers.

I'm looking into the second issue. It likely needs a bit more work to enable proper installation behavior in mingw/msys environments.

**Comment by SpaceIm** [comment]
> 1. The lib _must_ be installed with the dll. The lib file is actually an import library. Trying to use draco without the import library when BUILD_SHARED_LIBS is enabled will not work. It's required at link time when building executables that use the draco dll.

Sorry I don't understand. Obviously consumers need the import library at link time (and dll at runtime), but it doesn't have to be in the same folder than the dll, it's unrelated. Standard layout: import lib in lib folder, dll in bin folder, linker doesn't care at all.

**Comment by tomfinegan** [comment]
>  import lib in lib folder, dll in bin folder, linker doesn't care at all.

MSVC's linker needs to know where the import library and DLL are at link time. I'm not aware of a flag that allows you to tell the linker the import lib is in one place and the DLL is in another. I'm also not super interested in special casing this for MSVC because a package manager has a silly restriction regarding .lib files.

**Comment by SpaceIm** [comment]
This is not true. Linker doesn't care of dll location. Only import lib matters. The layout I suggest (which is followed by alsmot everybody by the way) is not specific to msvc, but windows in general (so also mingw).

**Comment by tomfinegan** [comment]
> This is not true. Linker doesn't care of dll location.

I stand corrected-- there was a mistake in my test program.

Feel free to submit a PR: I'm not certain your patch is complete as-is, but at least it's a starting point. From a quick glance the additional work needed on such a PR before acceptance would be: 

- It should be updated to use the local variables for bin_path and lib_path (if possible, but I don't see why hard coding would be req'd).
- It likely needs some additional handling for the case where lib and dylib are installed side-by-side (linux, at least).
