### ISSUE TITLE
JavaScript Decoder generate duplicated point at 'cube_att.obj'

### ISSUE THREAD

**Issue by mlenta** [google/draco#92]
I found that JavaScript Decoder generate a 'cube' with 24 points on your test data: https://raw.githubusercontent.com/google/draco/master/testdata/cube_att.obj

![cc](https://raw.githubusercontent.com/mlenta/reality/master/assets/cc.png)

.drc file is https://github.com/mlenta/reality/raw/master/assets/one.drc

Though it doesn't have any visual artifact, I am wondering whether it would affect performance.

I am using Firefox 47.0 on Linux Mint 18 Cinnamon 64-bit

**Comment by ondys** [comment]
There is 24 points because each cube corner has 3 different points. The cube contains normal vectors and each cube corner contains three different normal vectors that point to different directions. Note that internally, the positions for each cube corner are encoded as in one value only, but after decoding they end up being duplicated. This duplication is needed by most rendering engines (including three.js)
